// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfSyBgkkY3kvFWTH-n-DBD2ODO2VXxJCE',
    appId: '1:190125080236:web:9ef33f758b2a94c034e909',
    messagingSenderId: '190125080236',
    projectId: 'selfnotes-projects-flutter',
    authDomain: 'selfnotes-projects-flutter.firebaseapp.com',
    storageBucket: 'selfnotes-projects-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6603KYL6UMtkQEXklzCwxmpT8UW7Gf3Q',
    appId: '1:190125080236:android:868b80efd971d67034e909',
    messagingSenderId: '190125080236',
    projectId: 'selfnotes-projects-flutter',
    storageBucket: 'selfnotes-projects-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_F9jERrBRYWqcdX-UkVkgzIo44ZSboUY',
    appId: '1:190125080236:ios:411d7d1e880a692934e909',
    messagingSenderId: '190125080236',
    projectId: 'selfnotes-projects-flutter',
    storageBucket: 'selfnotes-projects-flutter.appspot.com',
    iosBundleId: 'com.learningFlutter.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_F9jERrBRYWqcdX-UkVkgzIo44ZSboUY',
    appId: '1:190125080236:ios:411d7d1e880a692934e909',
    messagingSenderId: '190125080236',
    projectId: 'selfnotes-projects-flutter',
    storageBucket: 'selfnotes-projects-flutter.appspot.com',
    iosBundleId: 'com.learningFlutter.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfSyBgkkY3kvFWTH-n-DBD2ODO2VXxJCE',
    appId: '1:190125080236:web:78d85edb4b22a7e934e909',
    messagingSenderId: '190125080236',
    projectId: 'selfnotes-projects-flutter',
    authDomain: 'selfnotes-projects-flutter.firebaseapp.com',
    storageBucket: 'selfnotes-projects-flutter.appspot.com',
  );
}
